CREATE TABLE FILM(
	ZEMLJA NVARCHAR2(30),
	F_NAZIV NVARCHAR2(100),
	F_TRAJANJE INT,
	F_GODINA INT,
	IME_REZISERA NVARCHAR2(50)
);

CREATE TABLE TERMIN_PROJEKCIJE(
	T_STATUS VARCHAR2(10),
	T_DATUM_I_VREME DATE,
	DIMENZIJA INT,
	F_NAZIV NVARCHAR2(100),
	F_TRAJANJE INT,
	F_GODINA INT
	
);

CREATE TABLE REZERVACIJA
(
	R_ID INT PRIMARY KEY,
	IME NVARCHAR2(25),
	PREZIME NVARCHAR2(25),
	CENA_REZERVACIJE INT,
	T_STATUS VARCHAR2(10),
	T_DATUM_I_VREME DATE
);

CREATE TABLE ULAZNICA
(
	ID INT PRIMARY KEY,
	CENA INT, 
	TIP VARCHAR2(20),
	BROJ_REDA INT,
	BROJ_SEDISTA INT,
	BROJ_SALE INT,
	T_STATUS VARCHAR2(10),
	T_DATUM_I_VREME DATE,
	R_ID INT
);

CREATE TABLE GLAVNE_ULOGE
(
	F_NAZIV NVARCHAR2(100),
	F_TRAJANJE INT,
	F_GODINA INT,
	IME NVARCHAR2(50)
);

CREATE TABLE ZANROVI
(
	F_NAZIV NVARCHAR2(100),
	F_TRAJANJE INT,
	F_GODINA INT,
	ZANR VARCHAR2(20)
);

ALTER TABLE FILM
	ADD CONSTRAINT FILM_PK PRIMARY KEY (F_NAZIV, F_TRAJANJE, F_GODINA);


ALTER TABLE TERMIN_PROJEKCIJE
	ADD CONSTRAINT T_PK PRIMARY KEY (T_STATUS, T_DATUM_I_VREME);
ALTER TABLE TERMIN_PROJEKCIJE
	ADD CONSTRAINT T_FK FOREIGN KEY (F_NAZIV, F_TRAJANJE, F_GODINA) REFERENCES FILM(F_NAZIV, F_TRAJANJE, F_GODINA);


ALTER TABLE REZERVACIJA
	ADD CONSTRAINT R_FK FOREIGN KEY (T_STATUS, T_DATUM_I_VREME) REFERENCES TERMIN_PROJEKCIJE(T_STATUS, T_DATUM_I_VREME);


ALTER TABLE ULAZNICA
	ADD CONSTRAINT U_FK1 FOREIGN KEY (T_STATUS, T_DATUM_I_VREME) REFERENCES TERMIN_PROJEKCIJE(T_STATUS, T_DATUM_I_VREME);
ALTER TABLE ULAZNICA
	ADD CONSTRAINT R_FK1 FOREIGN KEY (R_ID) REFERENCES REZERVACIJA(R_ID);


ALTER TABLE GLAVNE_ULOGE
	ADD CONSTRAINT F_FK FOREIGN KEY (F_NAZIV, F_TRAJANJE, F_GODINA) REFERENCES FILM(F_NAZIV, F_TRAJANJE, F_GODINA);
ALTER TABLE GLAVNE_ULOGE
	ADD CONSTRAINT PK PRIMARY KEY (F_NAZIV, F_TRAJANJE, F_GODINA, IME);

ALTER TABLE ZANROVI
	ADD CONSTRAINT PK_Z PRIMARY KEY (F_NAZIV, F_TRAJANJE, F_GODINA, ZANR);

ALTER TABLE ZANROVI
	ADD CONSTRAINT F_FK3 FOREIGN KEY (F_NAZIV, F_TRAJANJE, F_GODINA) REFERENCES FILM(F_NAZIV, F_TRAJANJE, F_GODINA);




